### ISSUE TITLE
SMB 3.0 on azure and linux

### ISSUE THREAD

**Issue by litvos** [ibm-messaging/mq-azure#2]
In the pacemaker configuration I read: 'Such a file share can be used by an MQ multi-instance queue manager running on Windows but it does not meet the requirements of a multi-instance queue manager running on Linux'. What is a main reason for that? Limited SMB support in Linux? Performance of the File Storage on Azure?

**Comment by john-colgrave** [comment]
At the time of writing that the Azure File Storage did not support the type of locking that a multi-instance queue manager running on Linux requires. I do not know if that is still the case.

**Comment by litvos** [comment]
thanks. understood.
