### ISSUE TITLE
AMQ6239 and AMQ7077 on crtmqm command

### ISSUE THREAD

**Issue by ConnorLightwell** [ibm-messaging/mq-azure#4]
I have created the share and used the cmdkey and netuse commands to map the drive successfully. I can create, delete and modify files on the share and I see it mapped on my VM.

However, when I run the 'crtmqm' command I'm presented with the following error:

**AMQ6239: Permission denied attempting to access filesystem location 'Y:\data'.

EXPLANATION:
An attempt to query the filesystem object identified failed because the command
issued did not have authority to access the object.
ACTION:
Check the authority on the object and of the user executing the command and
reissue the command.** 

Is there any more granular azure file permissions that can be checked i.e the ability to execute commands? 

No expert on azure file storage so anything however trivial may prove useful! Thanks

Connor Smith
Connor.smith@lightwellinc.com

**Comment by john-colgrave** [comment]
Did you import the storage credentials into your virtual machines, for all users that administer and run queue managers? See Step 3 in the guide "How to setup IBM MQ Multi instance queue manager with Microsoft Azure File Service" in the Wiki of this repository.

**Comment by ConnorLightwell** [comment]
Yes i used cmdkey to import storage credentials for my admin user and the service users.

A cmdkey /list command shows my file share is there:

 **Target: Domain:target=<MYSHARE>.file.core.windows.net
    Type: Domain Password
    User: <USER>**

I can map the drive from all necessary accounts using netuse on the command line and also via Windows explorer. and each user 'appears' to have full control on the files/folders i create.

Would there be any more users/groups that would need access? I am running MQ 9.0.0.3 within a Windows Domain, service accounts have been created and added to a 'Domain mqm' group as 
necessary.

Thanks,

Connor Smith
connor.smith@lightwellinc.com

**Comment by john-colgrave** [comment]
I expect using a Windows Domain makes a difference. Have a look at https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.0.0/com.ibm.mq.con.doc/q018150_.htm and try one of the approaches described there for Windows, and you may have to import the storage credentials in more/different environments. It has been a long time since I set up MQ Multi Instance on Azure and things have probably changed since then.

**Comment by ConnorLightwell** [comment]
Aha, crtmqm -a with my domain group did the trick.

Thanks for your help!
