### ISSUE TITLE
.NET Client and Advanced Message Security

### ISSUE THREAD

**Issue by sayanghosh123** [ibm-messaging/mq-azure#6]
We are working with MQ instances which are protected with AMS 
https://www.ibm.com/docs/en/ibm-mq/8.0?topic=s-mq-advanced-message-security

I have seen the sample client app that reads the MQ content and then pushes them to an Azure service. Is this client capable of decrypting AMS messages from MQ?
https://github.com/ibm-messaging/mq-azure/wiki/How-to-Send-message-from-an-on-premise-IBM-MQ-to-Azure-Service-Bus-queue

**Comment by ShashikanthRaoT** [comment]
Hello Sayan,

The MQ .NET client does not support AMS feature as documented [here](https://www.ibm.com/docs/pl/ibm-mq/9.2?topic=security-known-limitations-ams). However as documented in the same page, it's possible to enable AMS at the queue manager end with [Message Channel Agent Interception](https://www.ibm.com/docs/en/ibm-mq/9.2?topic=certificates-message-channel-agent-mca-interception). An example is also provided.

Hope that helps.
Shashi
